# mainatiner: nick.reva@snap.com
ENV["TERM"]="linux"

Vagrant.configure("2") do |config|
#test for Yi!
  # set up root access
  config.ssh.username = 'root'
  config.ssh.password = 'vagrant'
  config.ssh.insert_key = 'true'

  NodeCount = 5

  # configure Kubernetes Nodes
  (5..NodeCount).each do |i|
    config.vm.define "node#{i}" do |node|
      # set base image for the vagrant box
      config.vm.box = "opensuse/Leap-15.2.x86_64"

      # set the static IP for the vagrant box
      node.vm.network "private_network", ip: "192.168.56.10#{i}"
      # configure the parameters for VirtualBox provider
      node.vm.provider "virtualbox" do |v|
        v.name = "node#{i}"
        v.memory = 2048
        v.cpus = 2
      end

      # install docker and configure VM for rke installation
      config.vm.provision "shell", path: "bootstrap.sh"
    end
  end
end
